// megafunction wizard: %Shift register (RAM-based)%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altshift_taps 

// ============================================================
// File Name: screen_fifo.v
// Megafunction Name(s):
// 			altshift_taps
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 8.0 Build 215 05/29/2008 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2008 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altshift_taps DEVICE_FAMILY="Cyclone II" NUMBER_OF_TAPS=1 RAM_BLOCK_TYPE="M512" TAP_DISTANCE=797 WIDTH=30 clock shiftin shiftout taps lpm_hint="RAM_BLOCK_TYPE=M512"
//VERSION_BEGIN 8.0 cbx_altdpram 2008:03:07:257777 cbx_altshift_taps 2008:02:23:252825 cbx_altsyncram 2008:03:26:267331 cbx_cycloneii 2008:02:23:252825 cbx_lpm_add_sub 2008:03:09:257947 cbx_lpm_compare 2008:02:23:252825 cbx_lpm_counter 2008:02:23:252825 cbx_lpm_decode 2008:02:23:252825 cbx_lpm_mux 2008:02:23:252825 cbx_mgl 2008:04:11:273944 cbx_stratix 2008:02:23:252825 cbx_stratixii 2008:02:23:252825 cbx_stratixiii 2008:04:23:278548 cbx_util_mgl 2008:04:15:275689  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altsyncram ADDRESS_REG_B="CLOCK0" DEVICE_FAMILY="Cyclone II" NUMWORDS_A=795 NUMWORDS_B=795 OPERATION_MODE="DUAL_PORT" OUTDATA_REG_B="CLOCK0" RAM_BLOCK_TYPE="M512" READ_DURING_WRITE_MODE_MIXED_PORTS="OLD_DATA" WIDTH_A=30 WIDTH_B=30 WIDTH_BYTEENA_A=1 WIDTHAD_A=10 WIDTHAD_B=10 address_a address_b clock0 clocken0 data_a q_b wren_a
//VERSION_BEGIN 8.0 cbx_altsyncram 2008:03:26:267331 cbx_cycloneii 2008:02:23:252825 cbx_lpm_add_sub 2008:03:09:257947 cbx_lpm_compare 2008:02:23:252825 cbx_lpm_decode 2008:02:23:252825 cbx_lpm_mux 2008:02:23:252825 cbx_mgl 2008:04:11:273944 cbx_stratix 2008:02:23:252825 cbx_stratixii 2008:02:23:252825 cbx_stratixiii 2008:04:23:278548 cbx_util_mgl 2008:04:15:275689  VERSION_END

//synthesis_resources = M4K 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  screen_fifo_altsyncram
	( 
	address_a,
	address_b,
	clock0,
	clocken0,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */
		/* synthesis ALTERA_ATTRIBUTE="OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION" */;
	input   [9:0]  address_a;
	input   [9:0]  address_b;
	input   clock0;
	input   clocken0;
	input   [29:0]  data_a;
	output   [29:0]  q_b;
	input   wren_a;

	wire  [0:0]   wire_ram_block3a_0portbdataout;
	wire  [0:0]   wire_ram_block3a_1portbdataout;
	wire  [0:0]   wire_ram_block3a_2portbdataout;
	wire  [0:0]   wire_ram_block3a_3portbdataout;
	wire  [0:0]   wire_ram_block3a_4portbdataout;
	wire  [0:0]   wire_ram_block3a_5portbdataout;
	wire  [0:0]   wire_ram_block3a_6portbdataout;
	wire  [0:0]   wire_ram_block3a_7portbdataout;
	wire  [0:0]   wire_ram_block3a_8portbdataout;
	wire  [0:0]   wire_ram_block3a_9portbdataout;
	wire  [0:0]   wire_ram_block3a_10portbdataout;
	wire  [0:0]   wire_ram_block3a_11portbdataout;
	wire  [0:0]   wire_ram_block3a_12portbdataout;
	wire  [0:0]   wire_ram_block3a_13portbdataout;
	wire  [0:0]   wire_ram_block3a_14portbdataout;
	wire  [0:0]   wire_ram_block3a_15portbdataout;
	wire  [0:0]   wire_ram_block3a_16portbdataout;
	wire  [0:0]   wire_ram_block3a_17portbdataout;
	wire  [0:0]   wire_ram_block3a_18portbdataout;
	wire  [0:0]   wire_ram_block3a_19portbdataout;
	wire  [0:0]   wire_ram_block3a_20portbdataout;
	wire  [0:0]   wire_ram_block3a_21portbdataout;
	wire  [0:0]   wire_ram_block3a_22portbdataout;
	wire  [0:0]   wire_ram_block3a_23portbdataout;
	wire  [0:0]   wire_ram_block3a_24portbdataout;
	wire  [0:0]   wire_ram_block3a_25portbdataout;
	wire  [0:0]   wire_ram_block3a_26portbdataout;
	wire  [0:0]   wire_ram_block3a_27portbdataout;
	wire  [0:0]   wire_ram_block3a_28portbdataout;
	wire  [0:0]   wire_ram_block3a_29portbdataout;
	wire  [9:0]  address_a_wire;
	wire  [9:0]  address_b_wire;

	cycloneii_ram_block   ram_block3a_0
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_0portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_0.connectivity_checking = "OFF",
		ram_block3a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_0.mixed_port_feed_through_mode = "old",
		ram_block3a_0.operation_mode = "dual_port",
		ram_block3a_0.port_a_address_width = 10,
		ram_block3a_0.port_a_data_width = 1,
		ram_block3a_0.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_0.port_a_first_address = 0,
		ram_block3a_0.port_a_first_bit_number = 0,
		ram_block3a_0.port_a_last_address = 794,
		ram_block3a_0.port_a_logical_ram_depth = 795,
		ram_block3a_0.port_a_logical_ram_width = 30,
		ram_block3a_0.port_b_address_clock = "clock0",
		ram_block3a_0.port_b_address_width = 10,
		ram_block3a_0.port_b_data_out_clear = "none",
		ram_block3a_0.port_b_data_out_clock = "clock0",
		ram_block3a_0.port_b_data_width = 1,
		ram_block3a_0.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_0.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_0.port_b_first_address = 0,
		ram_block3a_0.port_b_first_bit_number = 0,
		ram_block3a_0.port_b_last_address = 794,
		ram_block3a_0.port_b_logical_ram_depth = 795,
		ram_block3a_0.port_b_logical_ram_width = 30,
		ram_block3a_0.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_0.ram_block_type = "AUTO",
		ram_block3a_0.lpm_type = "cycloneii_ram_block",
		ram_block3a_0.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_1
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_1portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_1.connectivity_checking = "OFF",
		ram_block3a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_1.mixed_port_feed_through_mode = "old",
		ram_block3a_1.operation_mode = "dual_port",
		ram_block3a_1.port_a_address_width = 10,
		ram_block3a_1.port_a_data_width = 1,
		ram_block3a_1.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_1.port_a_first_address = 0,
		ram_block3a_1.port_a_first_bit_number = 1,
		ram_block3a_1.port_a_last_address = 794,
		ram_block3a_1.port_a_logical_ram_depth = 795,
		ram_block3a_1.port_a_logical_ram_width = 30,
		ram_block3a_1.port_b_address_clock = "clock0",
		ram_block3a_1.port_b_address_width = 10,
		ram_block3a_1.port_b_data_out_clear = "none",
		ram_block3a_1.port_b_data_out_clock = "clock0",
		ram_block3a_1.port_b_data_width = 1,
		ram_block3a_1.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_1.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_1.port_b_first_address = 0,
		ram_block3a_1.port_b_first_bit_number = 1,
		ram_block3a_1.port_b_last_address = 794,
		ram_block3a_1.port_b_logical_ram_depth = 795,
		ram_block3a_1.port_b_logical_ram_width = 30,
		ram_block3a_1.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_1.ram_block_type = "AUTO",
		ram_block3a_1.lpm_type = "cycloneii_ram_block",
		ram_block3a_1.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_2
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_2portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_2.connectivity_checking = "OFF",
		ram_block3a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_2.mixed_port_feed_through_mode = "old",
		ram_block3a_2.operation_mode = "dual_port",
		ram_block3a_2.port_a_address_width = 10,
		ram_block3a_2.port_a_data_width = 1,
		ram_block3a_2.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_2.port_a_first_address = 0,
		ram_block3a_2.port_a_first_bit_number = 2,
		ram_block3a_2.port_a_last_address = 794,
		ram_block3a_2.port_a_logical_ram_depth = 795,
		ram_block3a_2.port_a_logical_ram_width = 30,
		ram_block3a_2.port_b_address_clock = "clock0",
		ram_block3a_2.port_b_address_width = 10,
		ram_block3a_2.port_b_data_out_clear = "none",
		ram_block3a_2.port_b_data_out_clock = "clock0",
		ram_block3a_2.port_b_data_width = 1,
		ram_block3a_2.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_2.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_2.port_b_first_address = 0,
		ram_block3a_2.port_b_first_bit_number = 2,
		ram_block3a_2.port_b_last_address = 794,
		ram_block3a_2.port_b_logical_ram_depth = 795,
		ram_block3a_2.port_b_logical_ram_width = 30,
		ram_block3a_2.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_2.ram_block_type = "AUTO",
		ram_block3a_2.lpm_type = "cycloneii_ram_block",
		ram_block3a_2.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_3
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_3portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_3.connectivity_checking = "OFF",
		ram_block3a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_3.mixed_port_feed_through_mode = "old",
		ram_block3a_3.operation_mode = "dual_port",
		ram_block3a_3.port_a_address_width = 10,
		ram_block3a_3.port_a_data_width = 1,
		ram_block3a_3.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_3.port_a_first_address = 0,
		ram_block3a_3.port_a_first_bit_number = 3,
		ram_block3a_3.port_a_last_address = 794,
		ram_block3a_3.port_a_logical_ram_depth = 795,
		ram_block3a_3.port_a_logical_ram_width = 30,
		ram_block3a_3.port_b_address_clock = "clock0",
		ram_block3a_3.port_b_address_width = 10,
		ram_block3a_3.port_b_data_out_clear = "none",
		ram_block3a_3.port_b_data_out_clock = "clock0",
		ram_block3a_3.port_b_data_width = 1,
		ram_block3a_3.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_3.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_3.port_b_first_address = 0,
		ram_block3a_3.port_b_first_bit_number = 3,
		ram_block3a_3.port_b_last_address = 794,
		ram_block3a_3.port_b_logical_ram_depth = 795,
		ram_block3a_3.port_b_logical_ram_width = 30,
		ram_block3a_3.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_3.ram_block_type = "AUTO",
		ram_block3a_3.lpm_type = "cycloneii_ram_block",
		ram_block3a_3.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_4
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_4portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_4.connectivity_checking = "OFF",
		ram_block3a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_4.mixed_port_feed_through_mode = "old",
		ram_block3a_4.operation_mode = "dual_port",
		ram_block3a_4.port_a_address_width = 10,
		ram_block3a_4.port_a_data_width = 1,
		ram_block3a_4.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_4.port_a_first_address = 0,
		ram_block3a_4.port_a_first_bit_number = 4,
		ram_block3a_4.port_a_last_address = 794,
		ram_block3a_4.port_a_logical_ram_depth = 795,
		ram_block3a_4.port_a_logical_ram_width = 30,
		ram_block3a_4.port_b_address_clock = "clock0",
		ram_block3a_4.port_b_address_width = 10,
		ram_block3a_4.port_b_data_out_clear = "none",
		ram_block3a_4.port_b_data_out_clock = "clock0",
		ram_block3a_4.port_b_data_width = 1,
		ram_block3a_4.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_4.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_4.port_b_first_address = 0,
		ram_block3a_4.port_b_first_bit_number = 4,
		ram_block3a_4.port_b_last_address = 794,
		ram_block3a_4.port_b_logical_ram_depth = 795,
		ram_block3a_4.port_b_logical_ram_width = 30,
		ram_block3a_4.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_4.ram_block_type = "AUTO",
		ram_block3a_4.lpm_type = "cycloneii_ram_block",
		ram_block3a_4.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_5
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_5portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_5.connectivity_checking = "OFF",
		ram_block3a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_5.mixed_port_feed_through_mode = "old",
		ram_block3a_5.operation_mode = "dual_port",
		ram_block3a_5.port_a_address_width = 10,
		ram_block3a_5.port_a_data_width = 1,
		ram_block3a_5.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_5.port_a_first_address = 0,
		ram_block3a_5.port_a_first_bit_number = 5,
		ram_block3a_5.port_a_last_address = 794,
		ram_block3a_5.port_a_logical_ram_depth = 795,
		ram_block3a_5.port_a_logical_ram_width = 30,
		ram_block3a_5.port_b_address_clock = "clock0",
		ram_block3a_5.port_b_address_width = 10,
		ram_block3a_5.port_b_data_out_clear = "none",
		ram_block3a_5.port_b_data_out_clock = "clock0",
		ram_block3a_5.port_b_data_width = 1,
		ram_block3a_5.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_5.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_5.port_b_first_address = 0,
		ram_block3a_5.port_b_first_bit_number = 5,
		ram_block3a_5.port_b_last_address = 794,
		ram_block3a_5.port_b_logical_ram_depth = 795,
		ram_block3a_5.port_b_logical_ram_width = 30,
		ram_block3a_5.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_5.ram_block_type = "AUTO",
		ram_block3a_5.lpm_type = "cycloneii_ram_block",
		ram_block3a_5.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_6
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_6portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_6.connectivity_checking = "OFF",
		ram_block3a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_6.mixed_port_feed_through_mode = "old",
		ram_block3a_6.operation_mode = "dual_port",
		ram_block3a_6.port_a_address_width = 10,
		ram_block3a_6.port_a_data_width = 1,
		ram_block3a_6.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_6.port_a_first_address = 0,
		ram_block3a_6.port_a_first_bit_number = 6,
		ram_block3a_6.port_a_last_address = 794,
		ram_block3a_6.port_a_logical_ram_depth = 795,
		ram_block3a_6.port_a_logical_ram_width = 30,
		ram_block3a_6.port_b_address_clock = "clock0",
		ram_block3a_6.port_b_address_width = 10,
		ram_block3a_6.port_b_data_out_clear = "none",
		ram_block3a_6.port_b_data_out_clock = "clock0",
		ram_block3a_6.port_b_data_width = 1,
		ram_block3a_6.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_6.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_6.port_b_first_address = 0,
		ram_block3a_6.port_b_first_bit_number = 6,
		ram_block3a_6.port_b_last_address = 794,
		ram_block3a_6.port_b_logical_ram_depth = 795,
		ram_block3a_6.port_b_logical_ram_width = 30,
		ram_block3a_6.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_6.ram_block_type = "AUTO",
		ram_block3a_6.lpm_type = "cycloneii_ram_block",
		ram_block3a_6.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_7
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_7portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_7.connectivity_checking = "OFF",
		ram_block3a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_7.mixed_port_feed_through_mode = "old",
		ram_block3a_7.operation_mode = "dual_port",
		ram_block3a_7.port_a_address_width = 10,
		ram_block3a_7.port_a_data_width = 1,
		ram_block3a_7.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_7.port_a_first_address = 0,
		ram_block3a_7.port_a_first_bit_number = 7,
		ram_block3a_7.port_a_last_address = 794,
		ram_block3a_7.port_a_logical_ram_depth = 795,
		ram_block3a_7.port_a_logical_ram_width = 30,
		ram_block3a_7.port_b_address_clock = "clock0",
		ram_block3a_7.port_b_address_width = 10,
		ram_block3a_7.port_b_data_out_clear = "none",
		ram_block3a_7.port_b_data_out_clock = "clock0",
		ram_block3a_7.port_b_data_width = 1,
		ram_block3a_7.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_7.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_7.port_b_first_address = 0,
		ram_block3a_7.port_b_first_bit_number = 7,
		ram_block3a_7.port_b_last_address = 794,
		ram_block3a_7.port_b_logical_ram_depth = 795,
		ram_block3a_7.port_b_logical_ram_width = 30,
		ram_block3a_7.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_7.ram_block_type = "AUTO",
		ram_block3a_7.lpm_type = "cycloneii_ram_block",
		ram_block3a_7.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_8
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[8]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_8portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_8.connectivity_checking = "OFF",
		ram_block3a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_8.mixed_port_feed_through_mode = "old",
		ram_block3a_8.operation_mode = "dual_port",
		ram_block3a_8.port_a_address_width = 10,
		ram_block3a_8.port_a_data_width = 1,
		ram_block3a_8.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_8.port_a_first_address = 0,
		ram_block3a_8.port_a_first_bit_number = 8,
		ram_block3a_8.port_a_last_address = 794,
		ram_block3a_8.port_a_logical_ram_depth = 795,
		ram_block3a_8.port_a_logical_ram_width = 30,
		ram_block3a_8.port_b_address_clock = "clock0",
		ram_block3a_8.port_b_address_width = 10,
		ram_block3a_8.port_b_data_out_clear = "none",
		ram_block3a_8.port_b_data_out_clock = "clock0",
		ram_block3a_8.port_b_data_width = 1,
		ram_block3a_8.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_8.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_8.port_b_first_address = 0,
		ram_block3a_8.port_b_first_bit_number = 8,
		ram_block3a_8.port_b_last_address = 794,
		ram_block3a_8.port_b_logical_ram_depth = 795,
		ram_block3a_8.port_b_logical_ram_width = 30,
		ram_block3a_8.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_8.ram_block_type = "AUTO",
		ram_block3a_8.lpm_type = "cycloneii_ram_block",
		ram_block3a_8.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_9
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[9]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_9portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_9.connectivity_checking = "OFF",
		ram_block3a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_9.mixed_port_feed_through_mode = "old",
		ram_block3a_9.operation_mode = "dual_port",
		ram_block3a_9.port_a_address_width = 10,
		ram_block3a_9.port_a_data_width = 1,
		ram_block3a_9.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_9.port_a_first_address = 0,
		ram_block3a_9.port_a_first_bit_number = 9,
		ram_block3a_9.port_a_last_address = 794,
		ram_block3a_9.port_a_logical_ram_depth = 795,
		ram_block3a_9.port_a_logical_ram_width = 30,
		ram_block3a_9.port_b_address_clock = "clock0",
		ram_block3a_9.port_b_address_width = 10,
		ram_block3a_9.port_b_data_out_clear = "none",
		ram_block3a_9.port_b_data_out_clock = "clock0",
		ram_block3a_9.port_b_data_width = 1,
		ram_block3a_9.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_9.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_9.port_b_first_address = 0,
		ram_block3a_9.port_b_first_bit_number = 9,
		ram_block3a_9.port_b_last_address = 794,
		ram_block3a_9.port_b_logical_ram_depth = 795,
		ram_block3a_9.port_b_logical_ram_width = 30,
		ram_block3a_9.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_9.ram_block_type = "AUTO",
		ram_block3a_9.lpm_type = "cycloneii_ram_block",
		ram_block3a_9.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_10
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[10]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_10portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_10.connectivity_checking = "OFF",
		ram_block3a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_10.mixed_port_feed_through_mode = "old",
		ram_block3a_10.operation_mode = "dual_port",
		ram_block3a_10.port_a_address_width = 10,
		ram_block3a_10.port_a_data_width = 1,
		ram_block3a_10.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_10.port_a_first_address = 0,
		ram_block3a_10.port_a_first_bit_number = 10,
		ram_block3a_10.port_a_last_address = 794,
		ram_block3a_10.port_a_logical_ram_depth = 795,
		ram_block3a_10.port_a_logical_ram_width = 30,
		ram_block3a_10.port_b_address_clock = "clock0",
		ram_block3a_10.port_b_address_width = 10,
		ram_block3a_10.port_b_data_out_clear = "none",
		ram_block3a_10.port_b_data_out_clock = "clock0",
		ram_block3a_10.port_b_data_width = 1,
		ram_block3a_10.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_10.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_10.port_b_first_address = 0,
		ram_block3a_10.port_b_first_bit_number = 10,
		ram_block3a_10.port_b_last_address = 794,
		ram_block3a_10.port_b_logical_ram_depth = 795,
		ram_block3a_10.port_b_logical_ram_width = 30,
		ram_block3a_10.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_10.ram_block_type = "AUTO",
		ram_block3a_10.lpm_type = "cycloneii_ram_block",
		ram_block3a_10.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_11
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[11]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_11portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_11.connectivity_checking = "OFF",
		ram_block3a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_11.mixed_port_feed_through_mode = "old",
		ram_block3a_11.operation_mode = "dual_port",
		ram_block3a_11.port_a_address_width = 10,
		ram_block3a_11.port_a_data_width = 1,
		ram_block3a_11.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_11.port_a_first_address = 0,
		ram_block3a_11.port_a_first_bit_number = 11,
		ram_block3a_11.port_a_last_address = 794,
		ram_block3a_11.port_a_logical_ram_depth = 795,
		ram_block3a_11.port_a_logical_ram_width = 30,
		ram_block3a_11.port_b_address_clock = "clock0",
		ram_block3a_11.port_b_address_width = 10,
		ram_block3a_11.port_b_data_out_clear = "none",
		ram_block3a_11.port_b_data_out_clock = "clock0",
		ram_block3a_11.port_b_data_width = 1,
		ram_block3a_11.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_11.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_11.port_b_first_address = 0,
		ram_block3a_11.port_b_first_bit_number = 11,
		ram_block3a_11.port_b_last_address = 794,
		ram_block3a_11.port_b_logical_ram_depth = 795,
		ram_block3a_11.port_b_logical_ram_width = 30,
		ram_block3a_11.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_11.ram_block_type = "AUTO",
		ram_block3a_11.lpm_type = "cycloneii_ram_block",
		ram_block3a_11.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_12
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[12]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_12portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_12.connectivity_checking = "OFF",
		ram_block3a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_12.mixed_port_feed_through_mode = "old",
		ram_block3a_12.operation_mode = "dual_port",
		ram_block3a_12.port_a_address_width = 10,
		ram_block3a_12.port_a_data_width = 1,
		ram_block3a_12.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_12.port_a_first_address = 0,
		ram_block3a_12.port_a_first_bit_number = 12,
		ram_block3a_12.port_a_last_address = 794,
		ram_block3a_12.port_a_logical_ram_depth = 795,
		ram_block3a_12.port_a_logical_ram_width = 30,
		ram_block3a_12.port_b_address_clock = "clock0",
		ram_block3a_12.port_b_address_width = 10,
		ram_block3a_12.port_b_data_out_clear = "none",
		ram_block3a_12.port_b_data_out_clock = "clock0",
		ram_block3a_12.port_b_data_width = 1,
		ram_block3a_12.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_12.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_12.port_b_first_address = 0,
		ram_block3a_12.port_b_first_bit_number = 12,
		ram_block3a_12.port_b_last_address = 794,
		ram_block3a_12.port_b_logical_ram_depth = 795,
		ram_block3a_12.port_b_logical_ram_width = 30,
		ram_block3a_12.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_12.ram_block_type = "AUTO",
		ram_block3a_12.lpm_type = "cycloneii_ram_block",
		ram_block3a_12.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_13
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[13]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_13portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_13.connectivity_checking = "OFF",
		ram_block3a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_13.mixed_port_feed_through_mode = "old",
		ram_block3a_13.operation_mode = "dual_port",
		ram_block3a_13.port_a_address_width = 10,
		ram_block3a_13.port_a_data_width = 1,
		ram_block3a_13.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_13.port_a_first_address = 0,
		ram_block3a_13.port_a_first_bit_number = 13,
		ram_block3a_13.port_a_last_address = 794,
		ram_block3a_13.port_a_logical_ram_depth = 795,
		ram_block3a_13.port_a_logical_ram_width = 30,
		ram_block3a_13.port_b_address_clock = "clock0",
		ram_block3a_13.port_b_address_width = 10,
		ram_block3a_13.port_b_data_out_clear = "none",
		ram_block3a_13.port_b_data_out_clock = "clock0",
		ram_block3a_13.port_b_data_width = 1,
		ram_block3a_13.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_13.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_13.port_b_first_address = 0,
		ram_block3a_13.port_b_first_bit_number = 13,
		ram_block3a_13.port_b_last_address = 794,
		ram_block3a_13.port_b_logical_ram_depth = 795,
		ram_block3a_13.port_b_logical_ram_width = 30,
		ram_block3a_13.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_13.ram_block_type = "AUTO",
		ram_block3a_13.lpm_type = "cycloneii_ram_block",
		ram_block3a_13.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_14
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[14]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_14portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_14.connectivity_checking = "OFF",
		ram_block3a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_14.mixed_port_feed_through_mode = "old",
		ram_block3a_14.operation_mode = "dual_port",
		ram_block3a_14.port_a_address_width = 10,
		ram_block3a_14.port_a_data_width = 1,
		ram_block3a_14.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_14.port_a_first_address = 0,
		ram_block3a_14.port_a_first_bit_number = 14,
		ram_block3a_14.port_a_last_address = 794,
		ram_block3a_14.port_a_logical_ram_depth = 795,
		ram_block3a_14.port_a_logical_ram_width = 30,
		ram_block3a_14.port_b_address_clock = "clock0",
		ram_block3a_14.port_b_address_width = 10,
		ram_block3a_14.port_b_data_out_clear = "none",
		ram_block3a_14.port_b_data_out_clock = "clock0",
		ram_block3a_14.port_b_data_width = 1,
		ram_block3a_14.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_14.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_14.port_b_first_address = 0,
		ram_block3a_14.port_b_first_bit_number = 14,
		ram_block3a_14.port_b_last_address = 794,
		ram_block3a_14.port_b_logical_ram_depth = 795,
		ram_block3a_14.port_b_logical_ram_width = 30,
		ram_block3a_14.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_14.ram_block_type = "AUTO",
		ram_block3a_14.lpm_type = "cycloneii_ram_block",
		ram_block3a_14.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_15
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[15]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_15portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_15.connectivity_checking = "OFF",
		ram_block3a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_15.mixed_port_feed_through_mode = "old",
		ram_block3a_15.operation_mode = "dual_port",
		ram_block3a_15.port_a_address_width = 10,
		ram_block3a_15.port_a_data_width = 1,
		ram_block3a_15.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_15.port_a_first_address = 0,
		ram_block3a_15.port_a_first_bit_number = 15,
		ram_block3a_15.port_a_last_address = 794,
		ram_block3a_15.port_a_logical_ram_depth = 795,
		ram_block3a_15.port_a_logical_ram_width = 30,
		ram_block3a_15.port_b_address_clock = "clock0",
		ram_block3a_15.port_b_address_width = 10,
		ram_block3a_15.port_b_data_out_clear = "none",
		ram_block3a_15.port_b_data_out_clock = "clock0",
		ram_block3a_15.port_b_data_width = 1,
		ram_block3a_15.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_15.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_15.port_b_first_address = 0,
		ram_block3a_15.port_b_first_bit_number = 15,
		ram_block3a_15.port_b_last_address = 794,
		ram_block3a_15.port_b_logical_ram_depth = 795,
		ram_block3a_15.port_b_logical_ram_width = 30,
		ram_block3a_15.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_15.ram_block_type = "AUTO",
		ram_block3a_15.lpm_type = "cycloneii_ram_block",
		ram_block3a_15.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_16
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[16]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_16portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_16.connectivity_checking = "OFF",
		ram_block3a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_16.mixed_port_feed_through_mode = "old",
		ram_block3a_16.operation_mode = "dual_port",
		ram_block3a_16.port_a_address_width = 10,
		ram_block3a_16.port_a_data_width = 1,
		ram_block3a_16.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_16.port_a_first_address = 0,
		ram_block3a_16.port_a_first_bit_number = 16,
		ram_block3a_16.port_a_last_address = 794,
		ram_block3a_16.port_a_logical_ram_depth = 795,
		ram_block3a_16.port_a_logical_ram_width = 30,
		ram_block3a_16.port_b_address_clock = "clock0",
		ram_block3a_16.port_b_address_width = 10,
		ram_block3a_16.port_b_data_out_clear = "none",
		ram_block3a_16.port_b_data_out_clock = "clock0",
		ram_block3a_16.port_b_data_width = 1,
		ram_block3a_16.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_16.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_16.port_b_first_address = 0,
		ram_block3a_16.port_b_first_bit_number = 16,
		ram_block3a_16.port_b_last_address = 794,
		ram_block3a_16.port_b_logical_ram_depth = 795,
		ram_block3a_16.port_b_logical_ram_width = 30,
		ram_block3a_16.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_16.ram_block_type = "AUTO",
		ram_block3a_16.lpm_type = "cycloneii_ram_block",
		ram_block3a_16.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_17
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[17]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_17portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_17.connectivity_checking = "OFF",
		ram_block3a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_17.mixed_port_feed_through_mode = "old",
		ram_block3a_17.operation_mode = "dual_port",
		ram_block3a_17.port_a_address_width = 10,
		ram_block3a_17.port_a_data_width = 1,
		ram_block3a_17.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_17.port_a_first_address = 0,
		ram_block3a_17.port_a_first_bit_number = 17,
		ram_block3a_17.port_a_last_address = 794,
		ram_block3a_17.port_a_logical_ram_depth = 795,
		ram_block3a_17.port_a_logical_ram_width = 30,
		ram_block3a_17.port_b_address_clock = "clock0",
		ram_block3a_17.port_b_address_width = 10,
		ram_block3a_17.port_b_data_out_clear = "none",
		ram_block3a_17.port_b_data_out_clock = "clock0",
		ram_block3a_17.port_b_data_width = 1,
		ram_block3a_17.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_17.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_17.port_b_first_address = 0,
		ram_block3a_17.port_b_first_bit_number = 17,
		ram_block3a_17.port_b_last_address = 794,
		ram_block3a_17.port_b_logical_ram_depth = 795,
		ram_block3a_17.port_b_logical_ram_width = 30,
		ram_block3a_17.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_17.ram_block_type = "AUTO",
		ram_block3a_17.lpm_type = "cycloneii_ram_block",
		ram_block3a_17.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_18
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[18]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_18portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_18.connectivity_checking = "OFF",
		ram_block3a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_18.mixed_port_feed_through_mode = "old",
		ram_block3a_18.operation_mode = "dual_port",
		ram_block3a_18.port_a_address_width = 10,
		ram_block3a_18.port_a_data_width = 1,
		ram_block3a_18.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_18.port_a_first_address = 0,
		ram_block3a_18.port_a_first_bit_number = 18,
		ram_block3a_18.port_a_last_address = 794,
		ram_block3a_18.port_a_logical_ram_depth = 795,
		ram_block3a_18.port_a_logical_ram_width = 30,
		ram_block3a_18.port_b_address_clock = "clock0",
		ram_block3a_18.port_b_address_width = 10,
		ram_block3a_18.port_b_data_out_clear = "none",
		ram_block3a_18.port_b_data_out_clock = "clock0",
		ram_block3a_18.port_b_data_width = 1,
		ram_block3a_18.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_18.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_18.port_b_first_address = 0,
		ram_block3a_18.port_b_first_bit_number = 18,
		ram_block3a_18.port_b_last_address = 794,
		ram_block3a_18.port_b_logical_ram_depth = 795,
		ram_block3a_18.port_b_logical_ram_width = 30,
		ram_block3a_18.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_18.ram_block_type = "AUTO",
		ram_block3a_18.lpm_type = "cycloneii_ram_block",
		ram_block3a_18.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_19
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[19]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_19portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_19.connectivity_checking = "OFF",
		ram_block3a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_19.mixed_port_feed_through_mode = "old",
		ram_block3a_19.operation_mode = "dual_port",
		ram_block3a_19.port_a_address_width = 10,
		ram_block3a_19.port_a_data_width = 1,
		ram_block3a_19.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_19.port_a_first_address = 0,
		ram_block3a_19.port_a_first_bit_number = 19,
		ram_block3a_19.port_a_last_address = 794,
		ram_block3a_19.port_a_logical_ram_depth = 795,
		ram_block3a_19.port_a_logical_ram_width = 30,
		ram_block3a_19.port_b_address_clock = "clock0",
		ram_block3a_19.port_b_address_width = 10,
		ram_block3a_19.port_b_data_out_clear = "none",
		ram_block3a_19.port_b_data_out_clock = "clock0",
		ram_block3a_19.port_b_data_width = 1,
		ram_block3a_19.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_19.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_19.port_b_first_address = 0,
		ram_block3a_19.port_b_first_bit_number = 19,
		ram_block3a_19.port_b_last_address = 794,
		ram_block3a_19.port_b_logical_ram_depth = 795,
		ram_block3a_19.port_b_logical_ram_width = 30,
		ram_block3a_19.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_19.ram_block_type = "AUTO",
		ram_block3a_19.lpm_type = "cycloneii_ram_block",
		ram_block3a_19.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_20
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[20]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_20portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_20.connectivity_checking = "OFF",
		ram_block3a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_20.mixed_port_feed_through_mode = "old",
		ram_block3a_20.operation_mode = "dual_port",
		ram_block3a_20.port_a_address_width = 10,
		ram_block3a_20.port_a_data_width = 1,
		ram_block3a_20.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_20.port_a_first_address = 0,
		ram_block3a_20.port_a_first_bit_number = 20,
		ram_block3a_20.port_a_last_address = 794,
		ram_block3a_20.port_a_logical_ram_depth = 795,
		ram_block3a_20.port_a_logical_ram_width = 30,
		ram_block3a_20.port_b_address_clock = "clock0",
		ram_block3a_20.port_b_address_width = 10,
		ram_block3a_20.port_b_data_out_clear = "none",
		ram_block3a_20.port_b_data_out_clock = "clock0",
		ram_block3a_20.port_b_data_width = 1,
		ram_block3a_20.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_20.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_20.port_b_first_address = 0,
		ram_block3a_20.port_b_first_bit_number = 20,
		ram_block3a_20.port_b_last_address = 794,
		ram_block3a_20.port_b_logical_ram_depth = 795,
		ram_block3a_20.port_b_logical_ram_width = 30,
		ram_block3a_20.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_20.ram_block_type = "AUTO",
		ram_block3a_20.lpm_type = "cycloneii_ram_block",
		ram_block3a_20.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_21
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[21]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_21portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_21.connectivity_checking = "OFF",
		ram_block3a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_21.mixed_port_feed_through_mode = "old",
		ram_block3a_21.operation_mode = "dual_port",
		ram_block3a_21.port_a_address_width = 10,
		ram_block3a_21.port_a_data_width = 1,
		ram_block3a_21.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_21.port_a_first_address = 0,
		ram_block3a_21.port_a_first_bit_number = 21,
		ram_block3a_21.port_a_last_address = 794,
		ram_block3a_21.port_a_logical_ram_depth = 795,
		ram_block3a_21.port_a_logical_ram_width = 30,
		ram_block3a_21.port_b_address_clock = "clock0",
		ram_block3a_21.port_b_address_width = 10,
		ram_block3a_21.port_b_data_out_clear = "none",
		ram_block3a_21.port_b_data_out_clock = "clock0",
		ram_block3a_21.port_b_data_width = 1,
		ram_block3a_21.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_21.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_21.port_b_first_address = 0,
		ram_block3a_21.port_b_first_bit_number = 21,
		ram_block3a_21.port_b_last_address = 794,
		ram_block3a_21.port_b_logical_ram_depth = 795,
		ram_block3a_21.port_b_logical_ram_width = 30,
		ram_block3a_21.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_21.ram_block_type = "AUTO",
		ram_block3a_21.lpm_type = "cycloneii_ram_block",
		ram_block3a_21.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_22
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[22]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_22portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_22.connectivity_checking = "OFF",
		ram_block3a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_22.mixed_port_feed_through_mode = "old",
		ram_block3a_22.operation_mode = "dual_port",
		ram_block3a_22.port_a_address_width = 10,
		ram_block3a_22.port_a_data_width = 1,
		ram_block3a_22.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_22.port_a_first_address = 0,
		ram_block3a_22.port_a_first_bit_number = 22,
		ram_block3a_22.port_a_last_address = 794,
		ram_block3a_22.port_a_logical_ram_depth = 795,
		ram_block3a_22.port_a_logical_ram_width = 30,
		ram_block3a_22.port_b_address_clock = "clock0",
		ram_block3a_22.port_b_address_width = 10,
		ram_block3a_22.port_b_data_out_clear = "none",
		ram_block3a_22.port_b_data_out_clock = "clock0",
		ram_block3a_22.port_b_data_width = 1,
		ram_block3a_22.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_22.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_22.port_b_first_address = 0,
		ram_block3a_22.port_b_first_bit_number = 22,
		ram_block3a_22.port_b_last_address = 794,
		ram_block3a_22.port_b_logical_ram_depth = 795,
		ram_block3a_22.port_b_logical_ram_width = 30,
		ram_block3a_22.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_22.ram_block_type = "AUTO",
		ram_block3a_22.lpm_type = "cycloneii_ram_block",
		ram_block3a_22.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_23
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[23]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_23portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_23.connectivity_checking = "OFF",
		ram_block3a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_23.mixed_port_feed_through_mode = "old",
		ram_block3a_23.operation_mode = "dual_port",
		ram_block3a_23.port_a_address_width = 10,
		ram_block3a_23.port_a_data_width = 1,
		ram_block3a_23.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_23.port_a_first_address = 0,
		ram_block3a_23.port_a_first_bit_number = 23,
		ram_block3a_23.port_a_last_address = 794,
		ram_block3a_23.port_a_logical_ram_depth = 795,
		ram_block3a_23.port_a_logical_ram_width = 30,
		ram_block3a_23.port_b_address_clock = "clock0",
		ram_block3a_23.port_b_address_width = 10,
		ram_block3a_23.port_b_data_out_clear = "none",
		ram_block3a_23.port_b_data_out_clock = "clock0",
		ram_block3a_23.port_b_data_width = 1,
		ram_block3a_23.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_23.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_23.port_b_first_address = 0,
		ram_block3a_23.port_b_first_bit_number = 23,
		ram_block3a_23.port_b_last_address = 794,
		ram_block3a_23.port_b_logical_ram_depth = 795,
		ram_block3a_23.port_b_logical_ram_width = 30,
		ram_block3a_23.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_23.ram_block_type = "AUTO",
		ram_block3a_23.lpm_type = "cycloneii_ram_block",
		ram_block3a_23.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_24
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[24]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_24portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_24.connectivity_checking = "OFF",
		ram_block3a_24.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_24.mixed_port_feed_through_mode = "old",
		ram_block3a_24.operation_mode = "dual_port",
		ram_block3a_24.port_a_address_width = 10,
		ram_block3a_24.port_a_data_width = 1,
		ram_block3a_24.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_24.port_a_first_address = 0,
		ram_block3a_24.port_a_first_bit_number = 24,
		ram_block3a_24.port_a_last_address = 794,
		ram_block3a_24.port_a_logical_ram_depth = 795,
		ram_block3a_24.port_a_logical_ram_width = 30,
		ram_block3a_24.port_b_address_clock = "clock0",
		ram_block3a_24.port_b_address_width = 10,
		ram_block3a_24.port_b_data_out_clear = "none",
		ram_block3a_24.port_b_data_out_clock = "clock0",
		ram_block3a_24.port_b_data_width = 1,
		ram_block3a_24.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_24.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_24.port_b_first_address = 0,
		ram_block3a_24.port_b_first_bit_number = 24,
		ram_block3a_24.port_b_last_address = 794,
		ram_block3a_24.port_b_logical_ram_depth = 795,
		ram_block3a_24.port_b_logical_ram_width = 30,
		ram_block3a_24.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_24.ram_block_type = "AUTO",
		ram_block3a_24.lpm_type = "cycloneii_ram_block",
		ram_block3a_24.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_25
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[25]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_25portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_25.connectivity_checking = "OFF",
		ram_block3a_25.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_25.mixed_port_feed_through_mode = "old",
		ram_block3a_25.operation_mode = "dual_port",
		ram_block3a_25.port_a_address_width = 10,
		ram_block3a_25.port_a_data_width = 1,
		ram_block3a_25.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_25.port_a_first_address = 0,
		ram_block3a_25.port_a_first_bit_number = 25,
		ram_block3a_25.port_a_last_address = 794,
		ram_block3a_25.port_a_logical_ram_depth = 795,
		ram_block3a_25.port_a_logical_ram_width = 30,
		ram_block3a_25.port_b_address_clock = "clock0",
		ram_block3a_25.port_b_address_width = 10,
		ram_block3a_25.port_b_data_out_clear = "none",
		ram_block3a_25.port_b_data_out_clock = "clock0",
		ram_block3a_25.port_b_data_width = 1,
		ram_block3a_25.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_25.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_25.port_b_first_address = 0,
		ram_block3a_25.port_b_first_bit_number = 25,
		ram_block3a_25.port_b_last_address = 794,
		ram_block3a_25.port_b_logical_ram_depth = 795,
		ram_block3a_25.port_b_logical_ram_width = 30,
		ram_block3a_25.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_25.ram_block_type = "AUTO",
		ram_block3a_25.lpm_type = "cycloneii_ram_block",
		ram_block3a_25.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_26
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[26]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_26portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_26.connectivity_checking = "OFF",
		ram_block3a_26.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_26.mixed_port_feed_through_mode = "old",
		ram_block3a_26.operation_mode = "dual_port",
		ram_block3a_26.port_a_address_width = 10,
		ram_block3a_26.port_a_data_width = 1,
		ram_block3a_26.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_26.port_a_first_address = 0,
		ram_block3a_26.port_a_first_bit_number = 26,
		ram_block3a_26.port_a_last_address = 794,
		ram_block3a_26.port_a_logical_ram_depth = 795,
		ram_block3a_26.port_a_logical_ram_width = 30,
		ram_block3a_26.port_b_address_clock = "clock0",
		ram_block3a_26.port_b_address_width = 10,
		ram_block3a_26.port_b_data_out_clear = "none",
		ram_block3a_26.port_b_data_out_clock = "clock0",
		ram_block3a_26.port_b_data_width = 1,
		ram_block3a_26.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_26.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_26.port_b_first_address = 0,
		ram_block3a_26.port_b_first_bit_number = 26,
		ram_block3a_26.port_b_last_address = 794,
		ram_block3a_26.port_b_logical_ram_depth = 795,
		ram_block3a_26.port_b_logical_ram_width = 30,
		ram_block3a_26.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_26.ram_block_type = "AUTO",
		ram_block3a_26.lpm_type = "cycloneii_ram_block",
		ram_block3a_26.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_27
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[27]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_27portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_27.connectivity_checking = "OFF",
		ram_block3a_27.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_27.mixed_port_feed_through_mode = "old",
		ram_block3a_27.operation_mode = "dual_port",
		ram_block3a_27.port_a_address_width = 10,
		ram_block3a_27.port_a_data_width = 1,
		ram_block3a_27.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_27.port_a_first_address = 0,
		ram_block3a_27.port_a_first_bit_number = 27,
		ram_block3a_27.port_a_last_address = 794,
		ram_block3a_27.port_a_logical_ram_depth = 795,
		ram_block3a_27.port_a_logical_ram_width = 30,
		ram_block3a_27.port_b_address_clock = "clock0",
		ram_block3a_27.port_b_address_width = 10,
		ram_block3a_27.port_b_data_out_clear = "none",
		ram_block3a_27.port_b_data_out_clock = "clock0",
		ram_block3a_27.port_b_data_width = 1,
		ram_block3a_27.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_27.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_27.port_b_first_address = 0,
		ram_block3a_27.port_b_first_bit_number = 27,
		ram_block3a_27.port_b_last_address = 794,
		ram_block3a_27.port_b_logical_ram_depth = 795,
		ram_block3a_27.port_b_logical_ram_width = 30,
		ram_block3a_27.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_27.ram_block_type = "AUTO",
		ram_block3a_27.lpm_type = "cycloneii_ram_block",
		ram_block3a_27.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_28
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[28]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_28portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_28.connectivity_checking = "OFF",
		ram_block3a_28.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_28.mixed_port_feed_through_mode = "old",
		ram_block3a_28.operation_mode = "dual_port",
		ram_block3a_28.port_a_address_width = 10,
		ram_block3a_28.port_a_data_width = 1,
		ram_block3a_28.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_28.port_a_first_address = 0,
		ram_block3a_28.port_a_first_bit_number = 28,
		ram_block3a_28.port_a_last_address = 794,
		ram_block3a_28.port_a_logical_ram_depth = 795,
		ram_block3a_28.port_a_logical_ram_width = 30,
		ram_block3a_28.port_b_address_clock = "clock0",
		ram_block3a_28.port_b_address_width = 10,
		ram_block3a_28.port_b_data_out_clear = "none",
		ram_block3a_28.port_b_data_out_clock = "clock0",
		ram_block3a_28.port_b_data_width = 1,
		ram_block3a_28.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_28.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_28.port_b_first_address = 0,
		ram_block3a_28.port_b_first_bit_number = 28,
		ram_block3a_28.port_b_last_address = 794,
		ram_block3a_28.port_b_logical_ram_depth = 795,
		ram_block3a_28.port_b_logical_ram_width = 30,
		ram_block3a_28.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_28.ram_block_type = "AUTO",
		ram_block3a_28.lpm_type = "cycloneii_ram_block",
		ram_block3a_28.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	cycloneii_ram_block   ram_block3a_29
	( 
	.clk0(clock0),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[29]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block3a_29portbdataout[0:0]),
	.portbrewe(1'b1)
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}})
	`ifdef FORMAL_VERIFICATION
	`else
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_29.connectivity_checking = "OFF",
		ram_block3a_29.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_29.mixed_port_feed_through_mode = "old",
		ram_block3a_29.operation_mode = "dual_port",
		ram_block3a_29.port_a_address_width = 10,
		ram_block3a_29.port_a_data_width = 1,
		ram_block3a_29.port_a_disable_ce_on_input_registers = "off",
		ram_block3a_29.port_a_first_address = 0,
		ram_block3a_29.port_a_first_bit_number = 29,
		ram_block3a_29.port_a_last_address = 794,
		ram_block3a_29.port_a_logical_ram_depth = 795,
		ram_block3a_29.port_a_logical_ram_width = 30,
		ram_block3a_29.port_b_address_clock = "clock0",
		ram_block3a_29.port_b_address_width = 10,
		ram_block3a_29.port_b_data_out_clear = "none",
		ram_block3a_29.port_b_data_out_clock = "clock0",
		ram_block3a_29.port_b_data_width = 1,
		ram_block3a_29.port_b_disable_ce_on_input_registers = "off",
		ram_block3a_29.port_b_disable_ce_on_output_registers = "off",
		ram_block3a_29.port_b_first_address = 0,
		ram_block3a_29.port_b_first_bit_number = 29,
		ram_block3a_29.port_b_last_address = 794,
		ram_block3a_29.port_b_logical_ram_depth = 795,
		ram_block3a_29.port_b_logical_ram_width = 30,
		ram_block3a_29.port_b_read_enable_write_enable_clock = "clock0",
		ram_block3a_29.ram_block_type = "AUTO",
		ram_block3a_29.lpm_type = "cycloneii_ram_block",
		ram_block3a_29.lpm_hint = "DONT_POWER_OPTIMIZE=ON";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block3a_29portbdataout[0], wire_ram_block3a_28portbdataout[0], wire_ram_block3a_27portbdataout[0], wire_ram_block3a_26portbdataout[0], wire_ram_block3a_25portbdataout[0], wire_ram_block3a_24portbdataout[0], wire_ram_block3a_23portbdataout[0], wire_ram_block3a_22portbdataout[0], wire_ram_block3a_21portbdataout[0], wire_ram_block3a_20portbdataout[0], wire_ram_block3a_19portbdataout[0], wire_ram_block3a_18portbdataout[0], wire_ram_block3a_17portbdataout[0], wire_ram_block3a_16portbdataout[0], wire_ram_block3a_15portbdataout[0], wire_ram_block3a_14portbdataout[0], wire_ram_block3a_13portbdataout[0], wire_ram_block3a_12portbdataout[0], wire_ram_block3a_11portbdataout[0], wire_ram_block3a_10portbdataout[0], wire_ram_block3a_9portbdataout[0], wire_ram_block3a_8portbdataout[0], wire_ram_block3a_7portbdataout[0], wire_ram_block3a_6portbdataout[0], wire_ram_block3a_5portbdataout[0], wire_ram_block3a_4portbdataout[0], wire_ram_block3a_3portbdataout[0], wire_ram_block3a_2portbdataout[0], wire_ram_block3a_1portbdataout[0], wire_ram_block3a_0portbdataout[0]};
endmodule //screen_fifo_altsyncram


//lpm_counter DEVICE_FAMILY="Cyclone II" lpm_direction="UP" lpm_modulus=795 lpm_port_updown="PORT_UNUSED" lpm_width=10 clk_en clock q
//VERSION_BEGIN 8.0 cbx_cycloneii 2008:02:23:252825 cbx_lpm_add_sub 2008:03:09:257947 cbx_lpm_compare 2008:02:23:252825 cbx_lpm_counter 2008:02:23:252825 cbx_lpm_decode 2008:02:23:252825 cbx_mgl 2008:04:11:273944 cbx_stratix 2008:02:23:252825 cbx_stratixii 2008:02:23:252825  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone II" LPM_WIDTH=10 ONE_INPUT_IS_CONSTANT="YES" aeb dataa datab
//VERSION_BEGIN 8.0 cbx_cycloneii 2008:02:23:252825 cbx_lpm_add_sub 2008:03:09:257947 cbx_lpm_compare 2008:02:23:252825 cbx_mgl 2008:04:11:273944 cbx_stratix 2008:02:23:252825 cbx_stratixii 2008:02:23:252825  VERSION_END

//synthesis_resources = lut 17 reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  screen_fifo_cntr
	( 
	clk_en,
	clock,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clk_en;
	input   clock;
	output   [9:0]  q;

	wire  [0:0]   wire_counter_comb_bita_0combout;
	wire  [0:0]   wire_counter_comb_bita_1combout;
	wire  [0:0]   wire_counter_comb_bita_2combout;
	wire  [0:0]   wire_counter_comb_bita_3combout;
	wire  [0:0]   wire_counter_comb_bita_4combout;
	wire  [0:0]   wire_counter_comb_bita_5combout;
	wire  [0:0]   wire_counter_comb_bita_6combout;
	wire  [0:0]   wire_counter_comb_bita_7combout;
	wire  [0:0]   wire_counter_comb_bita_8combout;
	wire  [0:0]   wire_counter_comb_bita_9combout;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire  [0:0]   wire_counter_comb_bita_2cout;
	wire  [0:0]   wire_counter_comb_bita_3cout;
	wire  [0:0]   wire_counter_comb_bita_4cout;
	wire  [0:0]   wire_counter_comb_bita_5cout;
	wire  [0:0]   wire_counter_comb_bita_6cout;
	wire  [0:0]   wire_counter_comb_bita_7cout;
	wire  [0:0]   wire_counter_comb_bita_8cout;
	wire  [0:0]   wire_counter_comb_bita_9cout;
	wire  [9:0]   wire_counter_reg_bit4a_regout;
	wire  [9:0]   wire_counter_reg_bit4a_sdata;
	reg	wire_cmpr5_aeb_int;
	wire	wire_cmpr5_aeb;
	wire	[9:0]	wire_cmpr5_dataa;
	wire	[9:0]	wire_cmpr5_datab;
	wire  aclr_actual;
	wire cnt_en;
	wire  compare_result;
	wire  cout_actual;
	wire [9:0]  data;
	wire  external_cin;
	wire  [9:0]  modulus_bus;
	wire  modulus_trigger;
	wire  [9:0]  s_val;
	wire  [9:0]  safe_q;
	wire sclr;
	wire sload;
	wire sset;
	wire  time_to_clear;
	wire  updown_dir;

	cycloneii_lcell_comb   counter_comb_bita_0
	( 
	.cin(external_cin),
	.combout(wire_counter_comb_bita_0combout[0:0]),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[0:0]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_0.lut_mask = 16'h5A90,
		counter_comb_bita_0.sum_lutc_input = "cin",
		counter_comb_bita_0.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(wire_counter_comb_bita_1combout[0:0]),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[1:1]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_1.lut_mask = 16'h5A90,
		counter_comb_bita_1.sum_lutc_input = "cin",
		counter_comb_bita_1.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_2
	( 
	.cin(wire_counter_comb_bita_1cout[0:0]),
	.combout(wire_counter_comb_bita_2combout[0:0]),
	.cout(wire_counter_comb_bita_2cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[2:2]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_2.lut_mask = 16'h5A90,
		counter_comb_bita_2.sum_lutc_input = "cin",
		counter_comb_bita_2.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_3
	( 
	.cin(wire_counter_comb_bita_2cout[0:0]),
	.combout(wire_counter_comb_bita_3combout[0:0]),
	.cout(wire_counter_comb_bita_3cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[3:3]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_3.lut_mask = 16'h5A90,
		counter_comb_bita_3.sum_lutc_input = "cin",
		counter_comb_bita_3.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_4
	( 
	.cin(wire_counter_comb_bita_3cout[0:0]),
	.combout(wire_counter_comb_bita_4combout[0:0]),
	.cout(wire_counter_comb_bita_4cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[4:4]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_4.lut_mask = 16'h5A90,
		counter_comb_bita_4.sum_lutc_input = "cin",
		counter_comb_bita_4.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_5
	( 
	.cin(wire_counter_comb_bita_4cout[0:0]),
	.combout(wire_counter_comb_bita_5combout[0:0]),
	.cout(wire_counter_comb_bita_5cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[5:5]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_5.lut_mask = 16'h5A90,
		counter_comb_bita_5.sum_lutc_input = "cin",
		counter_comb_bita_5.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_6
	( 
	.cin(wire_counter_comb_bita_5cout[0:0]),
	.combout(wire_counter_comb_bita_6combout[0:0]),
	.cout(wire_counter_comb_bita_6cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[6:6]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_6.lut_mask = 16'h5A90,
		counter_comb_bita_6.sum_lutc_input = "cin",
		counter_comb_bita_6.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_7
	( 
	.cin(wire_counter_comb_bita_6cout[0:0]),
	.combout(wire_counter_comb_bita_7combout[0:0]),
	.cout(wire_counter_comb_bita_7cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[7:7]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_7.lut_mask = 16'h5A90,
		counter_comb_bita_7.sum_lutc_input = "cin",
		counter_comb_bita_7.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_8
	( 
	.cin(wire_counter_comb_bita_7cout[0:0]),
	.combout(wire_counter_comb_bita_8combout[0:0]),
	.cout(wire_counter_comb_bita_8cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[8:8]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_8.lut_mask = 16'h5A90,
		counter_comb_bita_8.sum_lutc_input = "cin",
		counter_comb_bita_8.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_comb   counter_comb_bita_9
	( 
	.cin(wire_counter_comb_bita_8cout[0:0]),
	.combout(wire_counter_comb_bita_9combout[0:0]),
	.cout(wire_counter_comb_bita_9cout[0:0]),
	.dataa(wire_counter_reg_bit4a_regout[9:9]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_9.lut_mask = 16'h5A90,
		counter_comb_bita_9.sum_lutc_input = "cin",
		counter_comb_bita_9.lpm_type = "cycloneii_lcell_comb";
	cycloneii_lcell_ff   counter_reg_bit4a_0
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_0combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[0:0]),
	.sdata(wire_counter_reg_bit4a_sdata[0:0]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_1
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_1combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[1:1]),
	.sdata(wire_counter_reg_bit4a_sdata[1:1]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_2
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_2combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[2:2]),
	.sdata(wire_counter_reg_bit4a_sdata[2:2]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_3
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_3combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[3:3]),
	.sdata(wire_counter_reg_bit4a_sdata[3:3]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_4
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_4combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[4:4]),
	.sdata(wire_counter_reg_bit4a_sdata[4:4]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_5
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_5combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[5:5]),
	.sdata(wire_counter_reg_bit4a_sdata[5:5]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_6
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_6combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[6:6]),
	.sdata(wire_counter_reg_bit4a_sdata[6:6]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_7
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_7combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[7:7]),
	.sdata(wire_counter_reg_bit4a_sdata[7:7]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_8
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_8combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[8:8]),
	.sdata(wire_counter_reg_bit4a_sdata[8:8]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	cycloneii_lcell_ff   counter_reg_bit4a_9
	( 
	.aclr(aclr_actual),
	.clk(clock),
	.datain(wire_counter_comb_bita_9combout[0:0]),
	.ena((clk_en & (((sclr | sset) | sload) | cnt_en))),
	.regout(wire_counter_reg_bit4a_regout[9:9]),
	.sdata(wire_counter_reg_bit4a_sdata[9:9]),
	.sload((((sclr | sset) | sload) | modulus_trigger)),
	.sclr(1'b0)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	assign
		wire_counter_reg_bit4a_sdata = ({10{(~ sclr)}} & (({10{sset}} & s_val) | ({10{(~ sset)}} & (({10{sload}} & data) | (({10{(~ sload)}} & modulus_bus) & {10{(~ updown_dir)}})))));
	always @(wire_cmpr5_dataa or wire_cmpr5_datab)
	begin
		if (wire_cmpr5_dataa == wire_cmpr5_datab) 
			begin
				wire_cmpr5_aeb_int = 1'b1;
			end
		else
			begin
				wire_cmpr5_aeb_int = 1'b0;
			end
	end
	assign
		wire_cmpr5_aeb = wire_cmpr5_aeb_int;
	assign
		wire_cmpr5_dataa = safe_q,
		wire_cmpr5_datab = modulus_bus;
	assign
		aclr_actual = 1'b0,
		cnt_en = 1'b1,
		compare_result = wire_cmpr5_aeb,
		cout_actual = (wire_counter_comb_bita_9cout[0:0] | (time_to_clear & updown_dir)),
		data = {10{1'b0}},
		external_cin = 1'b1,
		modulus_bus = 10'b1100011010,
		modulus_trigger = cout_actual,
		q = safe_q,
		s_val = 10'b1111111111,
		safe_q = wire_counter_reg_bit4a_regout,
		sclr = 1'b0,
		sload = 1'b0,
		sset = 1'b0,
		time_to_clear = compare_result,
		updown_dir = 1'b1;
endmodule //screen_fifo_cntr

//synthesis_resources = lut 17 M4K 8 reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  screen_fifo_shift_taps
	( 
	clock,
	shiftin,
	shiftout,
	taps) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   [29:0]  shiftin;
	output   [29:0]  shiftout;
	output   [29:0]  taps;

	wire  [29:0]   wire_altsyncram2_q_b;
	wire  [9:0]   wire_cntr1_q;
	wire clken;

	screen_fifo_altsyncram   altsyncram2
	( 
	.address_a(wire_cntr1_q),
	.address_b(wire_cntr1_q),
	.clock0(clock),
	.clocken0(clken),
	.data_a({shiftin}),
	.q_b(wire_altsyncram2_q_b),
	.wren_a(1'b1));
	screen_fifo_cntr   cntr1
	( 
	.clk_en(clken),
	.clock(clock),
	.q(wire_cntr1_q));
	assign
		clken = 1'b1,
		shiftout = wire_altsyncram2_q_b[29:0],
		taps = wire_altsyncram2_q_b;
	initial/*synthesis enable_verilog_initial_construct*/
 	begin
		$display("Warning: Device family Cyclone II does not have M512 blocks -- using available memory blocks");
	end
endmodule //screen_fifo_shift_taps
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module screen_fifo (
	clock,
	shiftin,
	shiftout,
	taps)/* synthesis synthesis_clearbox = 1 */;

	input	  clock;
	input	[29:0]  shiftin;
	output	[29:0]  shiftout;
	output	[29:0]  taps;

	wire [29:0] sub_wire0;
	wire [29:0] sub_wire1;
	wire [29:0] taps = sub_wire0[29:0];
	wire [29:0] shiftout = sub_wire1[29:0];

	screen_fifo_shift_taps	screen_fifo_shift_taps_component (
				.clock (clock),
				.shiftin (shiftin),
				.taps (sub_wire0),
				.shiftout (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ACLR NUMERIC "0"
// Retrieval info: PRIVATE: CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: GROUP_TAPS NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: NUMBER_OF_TAPS NUMERIC "1"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: TAP_DISTANCE NUMERIC "797"
// Retrieval info: PRIVATE: WIDTH NUMERIC "30"
// Retrieval info: CONSTANT: LPM_HINT STRING "RAM_BLOCK_TYPE=M512"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altshift_taps"
// Retrieval info: CONSTANT: NUMBER_OF_TAPS NUMERIC "1"
// Retrieval info: CONSTANT: TAP_DISTANCE NUMERIC "797"
// Retrieval info: CONSTANT: WIDTH NUMERIC "30"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL clock
// Retrieval info: USED_PORT: shiftin 0 0 30 0 INPUT NODEFVAL shiftin[29..0]
// Retrieval info: USED_PORT: shiftout 0 0 30 0 OUTPUT NODEFVAL shiftout[29..0]
// Retrieval info: USED_PORT: taps 0 0 30 0 OUTPUT NODEFVAL taps[29..0]
// Retrieval info: CONNECT: @shiftin 0 0 30 0 shiftin 0 0 30 0
// Retrieval info: CONNECT: shiftout 0 0 30 0 @shiftout 0 0 30 0
// Retrieval info: CONNECT: taps 0 0 30 0 @taps 0 0 30 0
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo_waveforms.html TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo_wave*.jpg FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL screen_fifo_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
